version: '3'

volumes:
  postgres_data: {}

services:
  postgres:
    image: postgres
    volumes:
      - postgres_data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=djangosample
      - POSTGRES_USER=sampleuser
      - POSTGRES_PASSWORD=samplesecret

  django:
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile-dev
    volumes:
      - ./app:/app
    command: ["./manage.py", "runserver", "0:8000"]
    links:
      - postgres:db
    ports:
      - 8000:8000
    restart: always
